### PR TITLE
Refactor tasks into separate roles

### PR DESCRIPTION
**Pull request by geoand**
This PR refactors the whole structure of the playbook to use two different role, `minishift` and `istio`.

The operations performed are the same as before, however there are now two significant changes (besides obviously the structure of the project):
- The `istio` role is dependent on the `minishift` role, meaning that even when on executes the `istio` role, the `minishift` role gets executed as well.
- Due to the tight coupling of the two roles, the experience of running of the demo is seamless. One can easily run and rerun the playbook without having to worry about the state of the local system.

The downside to this approach is that the user cannot use a different installation of Openshift.
I am confident however that with a little extra work, the aforementioned limitation can be lifted, so consider this WIP :)

### CODE REVIEW

**Comment by cmoulliard** [comment]
> meaning that even when on executes the istio role, the minishift role gets executed as well.

Is it mandatory ? As a user has potentially already installed minishift separately, can we still use the istio role in an independent way ?

**Comment by geoand** [comment]
The fact that the minishift role get's executed does not mean that the minishift will be reinstalled every time. The role will not reinstall the binary if it finds that it's already installed, nor will it recreate the VM if it's already running. It tries to reuse as much of the system as possible.

So for user's that have already installed Minishift, there is no problem.
What I am mostly concerned about is users who will want to execute the playbook in order to install Istio on a regular Openshift cluster. Currently the playbook is not able to handle such a case.

**Comment by geoand** [comment]
I updated the code in the PR, so now the `istio` role is not tightly coupled to the `minishift` role.
By default the former role will not invoke the latter, however if such behavior is necessary, it can be configured as has been documented in the Readme

**Comment by geoand** [comment]
I updated this PR to incorporate the changes that were put in place by #7  as well

**Pull request merged**
